### ISSUE TITLE
hangs when not provided "args"

### ISSUE THREAD

**Issue by stephenmathieson** [segmentio/rpc-cli#4]
this hangs forever:

```
∴ go run cmd/rpc/main.go http://localhost:8004/rpc Something.GetOne
```

**Comment by yields** [comment]
ah damn, does this work?

```
go run cmd/rpc/main.go http://localhost:8004/rpc Something.GetOne null
```

even if it is, it's ugly, maybe we should add a fix that
1. if arguments is nil and stdin is empty send `null`
2. otherwise read and send `stdin`
