### ISSUE TITLE
error: invalid character 'H' looking for beginning of value

### ISSUE THREAD

**Issue by stephenmathieson** [segmentio/rpc-cli#8]
getting a strange error i haven't been able to make any sense of:

```
~/dev/src/github.com/segmentio/rpc-cli on master ∴ go run cmd/rpc/main.go :4007 Mtu.CalculateWorkspacePeriod foo=bar
rpc: invalid character 'H' looking for beginning of value
exit status 1
```

... any ideas?

**Comment by dominicbarnes** [comment]
For JSON-RPC v2 services, you have to specify the entire URL scheme. (default is a TCP JSON-RPC v1)

ie: `$ rpc http://localhost:4007/rpc Mtu.CalculateWorkspacePeriod foo=bar`

(note, you also need the `/rpc` path since we set that for all our JSON-RPC v2 services)

**Comment by stephenmathieson** [comment]
lololol forgot we have some v1 services and some v2

thanks dom
